logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    com.nimbusds: DEBUG
server:
  port: 8080
spring:
  application:
    name: Authorization-Server
  authorization-server:
    issuer-uri: http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  session:
    store-type: jdbc
auths:
  clients:
    artificer:
      keypass: 123456
      storepass: 123456
      alias: artificer
      path: keystore/artificer.jks
    matrix:
      keypass: 123456
      storepass: 123456
      alias: matrix
      path: keystore/matrix.jks
    internal:
      keypass: 123456
      storepass: 123456
      alias: internal
      path: keystore/internal.jks